Add reload capability to init script

diff --git a/traffic_stats/traffic_stats.init b/traffic_stats/traffic_stats.init
--- a/traffic_stats/traffic_stats.init
+++ b/traffic_stats/traffic_stats.init
@@ -9,8 +9,8 @@
 
 ### BEGIN INIT INFO
 # Provides: traffic_stats
-# Required-Start: 
-# Should-Start: 
+# Required-Start:
+# Should-Start:
 # Required-Stop:
 # Default-Start: 3 4 5
 # Default-Stop: 0 1 2 6
@@ -24,7 +24,7 @@ STATUS_RUNNING=1
 start()
 {
 	status
-	# check status return code 
+	# check status return code
 	if [[ $? -eq $STATUS_STOPPED || "$1" == "force" ]] ; then
 		echo "Starting traffic_stats."
 		ulimit -n 4096
@@ -40,17 +40,31 @@ stop()
 
 	# check status return code
 	if [[ $? -eq $STATUS_RUNNING || "$1" == "force" ]] ; then
-		echo "Stopping traffic_stats client.."
+		echo "Stopping traffic_stats client..."
 		kill `pidof -s traffic_stats`
-			
-	status
-	
+
+		status
+
 		if [ $? -eq $STATUS_STOPPED ]; then
 			echo "traffic_stats killed"
-			
 		else
 			echo "unable to identify and kill traffic_stats"
 		fi
+	fi
+
+	return $?
+}
+
+reload()
+{
+	status
+
+	# check status return code
+	if [[ $? -eq $STATUS_RUNNING ]] ; then
+		echo "Reloading traffic_stats client..."
+		kill -HUP `pidof -s traffic_stats`
+	else
+		echo "traffic_stats not running."
 	fi
 
 	return $?
@@ -61,11 +75,11 @@ status()
 	pid=`pidof -s traffic_stats`
 
 	if [ -n "$pid" ] ; then
-		echo "traffic_stats (pid $pid) is running.."
+		echo "traffic_stats (pid $pid) is running..."
 		return $STATUS_RUNNING
 	fi
 
-	echo "traffic_stats is stopped.."
+	echo "traffic_stats is stopped..."
 	return $STATUS_STOPPED
 }
 
@@ -76,6 +90,9 @@ case "$1" in
 	stop)
 		stop
 		;;
+	reload)
+		reload
+		;;
 	restart)
 		stop "force"
 		start "force"
@@ -84,7 +101,7 @@ case "$1" in
 		status
 		;;
 	*)
-		echo "Usage: $0 (start|stop|restart|status)"
+		echo "Usage: $0 (start|stop|reload|restart|status)"
 		exit 1
 esac
 
