adds check for connecting to psql as postgres user

diff --git a/traffic_ops/install/bin/postinstall b/traffic_ops/install/bin/postinstall
--- a/traffic_ops/install/bin/postinstall
+++ b/traffic_ops/install/bin/postinstall
@@ -22,6 +22,11 @@ for p in git go; do
 	type $p >/dev/null 2>&1 || { echo >&2 "postinstall requires $p but it's not installed.  Aborting."; exit 1; }
 done
 
+if [[ ! $(su - postgres psql -w -c 'show is_superuser' </dev/null 2>/dev/null) =~ 'on' ]]; then
+	echo >&2 "postinstall requires the postgres user to have superuser access to postgresql. Aborting."
+	exit 1
+fi
+
 # install carton first
 cpanm Carton
 
