Run Traffic Router Ultimate Test Harness directly from workflow file

diff --git a/.github/workflows/tr-ultimate-test-harness.yml b/.github/workflows/tr-ultimate-test-harness.yml
--- a/.github/workflows/tr-ultimate-test-harness.yml
+++ b/.github/workflows/tr-ultimate-test-harness.yml
@@ -184,7 +184,25 @@ jobs:
           fi
 
       - name: Run Traffic Router Ultimate Test Harness
-        run: ./.github/actions/tr-ultimate-test-harness/tr-ultimate-test-harness.sh
+        run: |
+          trap 'echo "Error on line ${LINENO} of ${0}"; exit 1' ERR
+          set -o errexit -o nounset -o pipefail
+
+          http_result=0 dns_result=0
+          http_requests_threshold=1200
+          dns_requests_threshold=2500
+          if ! ./ultimate-test-harness.test -test.v -test.run=^TestHTTPLoad$ -http_requests_threshold "$http_requests_threshold"; then
+              http_result=1
+          fi
+          if ! ./ultimate-test-harness.test -test.v -test.run=^TestDNSLoad$ -dns_requests_threshold "$dns_requests_threshold"; then
+              dns_result=1
+          fi
+          if [[ $http_result -eq 0 && $dns_result -eq 0 ]]; then echo
+              echo Tests passed!
+          else
+              echo Tests failed!
+              exit 1
+          fi
       - name: Write Dev CDN-in-a-Box logs to files
         run: |
           set -o errexit -o nounset
