Set interface IP addresses in a separate step

diff --git a/.github/workflows/tr-ultimate-test-harness.yml b/.github/workflows/tr-ultimate-test-harness.yml
--- a/.github/workflows/tr-ultimate-test-harness.yml
+++ b/.github/workflows/tr-ultimate-test-harness.yml
@@ -80,6 +80,72 @@ jobs:
             ${{ runner.os }}-node-modules-
       - name: Start the Dev CDN in a Box
         run: docker-compose up -d
+      - name: Set interface IP addresses
+        run: |2
+          trap 'echo "Error on line ${LINENO} of setting interface IP addresses"; exit 1' ERR
+          # set -o xtrace
+          # uncomment this line ^ to check interface data
+          set -o errexit -o nounset -o pipefail
+
+          # Get atc-ready function
+          source dev/atc.dev.sh
+          export -f atc-ready
+
+          echo 'Waiting until Traffic Ops is ready to accept requests...'
+          if ! timeout 10m bash -c 'atc-ready -w'; then
+            echo 'Traffic Ops was not available within 10 minutes!'
+            trap - ERR
+            echo 'Exiting...'
+            exit 1
+          fi
+
+          source infrastructure/cdn-in-a-box/traffic_ops/to-access.sh
+
+          declare -A service_by_hostname
+          service_by_hostname[trafficrouter]=trafficrouter
+          service_by_hostname[edge]=t3c
+
+          for hostname in trafficrouter edge; do
+            container_id="$(docker-compose ps -q "${service_by_hostname[$hostname]}")"
+            interface="$(<<'JSON' jq
+            {
+              "mtu": 1500,
+              "monitor": true,
+              "ipAddresses": [],
+              "name": "eth0"
+            }
+          JSON
+            )"
+            docker_network="$(docker network inspect dev.ciab.test)"
+            for ip_address_field in IPv4Address IPv6Address; do
+              ip_address="$(<<<"$docker_network" jq -r --arg CONTAINER_ID "$container_id" --arg IP_ADDRESS_FIELD "$ip_address_field" '.[0].Containers[$CONTAINER_ID][$IP_ADDRESS_FIELD]')"
+              if [[ "$ip_address" == null ]]; then
+                echo "Could not find ${ip_address_field} for ${hostname} service!"
+                exit 1
+              fi
+              interface="$(<<<"$interface" jq --arg IP_ADDRESS "$ip_address" '.ipAddresses += [{} | .address = $IP_ADDRESS | .serviceAddress = true]')"
+            done
+
+            # Get server JSON
+            server="$(to-get "api/$TO_API_VERSION/servers?hostName=${hostname}" | jq '.response[0]')"
+            if [[ -z "$server" ]]; then
+              echo "Could not get JSON for server ${hostname}"
+              exit 1
+            fi
+
+            # Update server's interface with its IP addresses
+            server="$(<<<"$server" jq ".interfaces = [${interface}]")"
+            server_id="$(<<<"$server" jq .id)"
+            if ! to-put "api/$TO_API_VERSION/servers/${server_id}" "$server"; then
+              echo "Could not update server ${hostname} with ${server}"
+              exit 1
+            fi
+          done
+
+          # Snapshot
+          cdn_id="$(<<<"$server" jq .cdnId)"
+          to-put "api/$TO_API_VERSION/snapshot?cdnID=${cdn_id}"
+
       - name: Run Traffic Router Ultimate Test Harness
         run: ./.github/actions/tr-ultimate-test-harness/tr-ultimate-test-harness.sh
       - name: Write Dev CDN-in-a-Box logs to files
